apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: my-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-grafana
  template:
    metadata:
      labels:
        app: my-grafana
    spec:
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-volume-claim
      containers:
      - name: grafana-container
        image: grafana/grafana:latest 
        ports:
        - containerPort: 3000         
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
